name: Check

on:
  workflow_dispatch:
    inputs:
      STOCK_DEVICE:
        description: "Your own device model or None"
        required: true
        default: "SM-A225F"

      STOCK_DEVICE_CSC_OR_DOWNLOAD_LINK:
        description: "Input stock device CSC code or direct download link."
        required: true
        default: "BKD"

      STOCK_FW_VERSION:
        description: "Specific Samsung firmware version (PDA/CSC/MODEM) OR (AP/CSC/CP)"
        required: false


jobs:
  build:
    name: Start QuantumROM Tools
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "FIRM_DIR=$(pwd)/FW" | tee -a "$GITHUB_ENV"
          echo "OUT_DIR=$(pwd)/OUT" | tee -a "$GITHUB_ENV"
          echo "WORK_DIR=$(pwd)/WORK" | tee -a "$GITHUB_ENV"
          echo "APKTOOL=$(pwd)/bin/java/apktool.jar" | tee -a "$GITHUB_ENV"
          echo "STOCK_DEVICE=${{ inputs.STOCK_DEVICE }}" | tee -a "$GITHUB_ENV"
          echo "STOCK_DEVICE_CSC_OR_DOWNLOAD_LINK=${{ inputs.STOCK_DEVICE_CSC_OR_DOWNLOAD_LINK }}" | tee -a "$GITHUB_ENV"
          echo "STOCK_FW_VERSION=${{ inputs.STOCK_FW_VERSION }}" | tee -a "$GITHUB_ENV"

      - name: Install Dependencies.
        run: |
          sudo apt update
          sudo apt install -y linux-modules-extra-$(uname -r)
          sudo modprobe f2fs || true

      - name: Extract f2fs img
        run: |
          sudo bash $(pwd)/extract_img.sh" odm.img "$FIRM_DIR"
